@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">Terms and Conditions</div>

				<div class="panel-body">
					<p><b>Instantpro terms and conditions</b></p>

					<p>The website operated at <a href="https://instantpro.ug/">https://instantpro.ug/</a> and such other locations as made available from time to time (collectively, the <b>"Website"</b>) and the Instantpro Mobile Applications (the <b>"App"</b>) and the services offered there from (collectively, the <b>"Service"</b>) are operated by Instantpro (U) Ltd and its corporate affiliates (collectively, <b>"us"</b>, <b>"we"</b> or the <b>"Instantpro Company"</b>).</p>

					<p><b>These terms of service set forth the general terms and conditions of your use of the Website, the App and our Services and are in addition to (not in lieu of) any other terms of use posted on </b><a href="https://instantpro.ug/"><b>https://Instantpro.ug/</b></a><b>, in connection with the App, and linked from our Terms and Conditions page at </b><a href="https://instantpro.com/terms_and_conditions"><b>https://Instantpro.com/terms_and_conditions</b></a><b>, which together constitute the entire Agreement (the "Agreement") between us and you ("you"). By accessing or using the Service, you (together with all persons accessing or using the Service, collectively, the "Users") signify that you have read, understand and agree to be bound by this Agreement in all respects with respect to the Website, the App, our provision of the Service, and your use of them.</b></p>

					<p><b>YOU MAY NOT USE THE SERVICES IF YOU ARE UNDER THE AGE OF MAJORITY IN THE JURISDICTION IN WHICH YOU ARE RESIDENT (I.E., IF YOU ARE A MINOR).</b></p>

					<p><b>PLEASE READ THIS AGREEMENT CAREFULLY AS IT CONTAINS IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, REMEDIES AND OBLIGATIONS. THESE INCLUDE, BUT ARE NOT LIMITED TO, VARIOUS LIMITATIONS AND EXCLUSIONS, AND INDEMNITIES.</b></p>

					<p>1. <b>About the Service</b>. The Service enables Users who are seeking help (<b>"Requesting Users"</b>) with various services, including those around the home to connect through the Website or App with third party service professionals (the <b>"Instant Professionals"</b>) who would like to complete the task (the <b>"Home Service"</b>) for the Requesting User. The Service provides a platform that connects Requesting Users and Home Service Professionals only. We do not provide or perform Home Services. We are not responsible for the performance of Home Services, nor do we have control over the quality, timing, provision or failure to provide, or any aspect whatsoever relating to the identification, request, or provision of Home Services related, directly or indirectly, to our Service. You must become a registered User by creating a User Account (as defined below) to request assistance and connect with a Home Service Professional. You may access the Service from a computer or mobile device.</p>

					<p>a. <b>Requesting Home Services</b>. A User may use the Service to post a request to have a particular Home Service provided (a <b>"Request"</b>). Such Requests must be clearly worded, correctly provide for the relevant category of service, and be a fair and accurate description of the work to be done. When making a request, the Requesting User is solely responsible for confirming the accuracy of all information provided, including, the work requested to be done and the location at which the Requesting User will require such Home Services (the <b>"Premises"</b>). Each Request is limited to one discrete Home Service to be provided by one or more Home Service Professionals. If a User wishes to obtain help with more than one Home Service, the User must use the <b>multiple services icon </b>as opposed to the individual service icons. As a Requesting User, by confirming your Request, you understand and agree that you have made an offer, for which we have the power to accept or reject in our sole discretion. Once you have confirmed your Request, you may cancel the job (<b>"Job"</b>) without incurring a fee only before such time that the Instant Professional has departed his or her current location for the Premises. You further acknowledge and understand that the first Instant Professional to whom we assign the request on the terms of your Request may be the Instant Professional to perform the Home Service. You understand that once we assign your request to a professional and he/she subsequently accepts it, we will notify you with information about the Instant Professional, which may include the Instant Professional's name, photo, company name, customer service rating, and/or estimated time of arrival. You will also be able to contact the Instant Professional by telephone or text message for the sole purpose of communication related to the Home Service Request.</p>

					<p>b. <b>Your Responsibilities</b>. By making a Request, you represent and warrant that you have the right to grant the Instant Professional and/or his team access to the Premises to perform the Home Services, will be present at the Premises or will have a representative who is 18 years old or older present at the Premises at all times while the Home Service is being performed.</p>

					<p>c. <b>Timing and the Instant Professional</b>. There are two timelines available to Requesting Users: (i) <b>"Urgent"</b>, and (ii) <b>"Later"</b>. We will take reasonable efforts, but are under no obligation, to connect you with an Instant Professional who is available to provide the Home Services provided in your Request, subject to your location, the Home Service requested, the availability of Instant Professionals willing to accept the Home Service Requested by you, and other conditions beyond our control. We do not guarantee that your Request will be accepted within the timeline prescribed for the respective service category, or at all. Any references within the Service to an Instant Professional being rated, verified, vetted, licensed (where applicable), qualified, or similar language only indicates that the Instant Professional has completed the relevant registration process and does not endorse, certify, or guarantee any User or their identity, trustworthiness, suitability, or ability to provide the Home Service. When interacting with other Users, including Instant Professionals, you should exercise due diligence, caution and common sense to protect your personal safety and property. NEITHER THE INSTANTPRO COMPANIES NOR OUR AFFILIATES OR LICENSORS ARE RESPONSIBLE FOR THE CONDUCT, WHETHER ONLINE OR OFFLINE, OF ANY USER OF THE SERVICE AND YOU HEREBY RELEASE THE INSTANTPRO COMPANIES AND OUR AFFILIATES OR LICENSORS FROM ANY LIABILITY RELATED THERETO, WHETHER DIRECT OR INDIRECT. THE INSTANTPRO COMPANIES AND OUR AFFILIATES AND LICENSORS WILL NOT BE LIABLE FOR ANY CLAIM, INJURY, OR DAMAGE ARISING IN CONNECTION WITH YOUR USE OF THE SERVICE.</p>

					<p>d. <b>Cancelling Home Services</b>. A Requesting User may cancel a Request without penalty before receiving a notification that an Instant Professional has accepted the Request. Any cancellation by a Requesting User or an Instant Professional for any reason whatsoever, must comply with the Guidelines. Any cancellation made in violation of the Guidelines will incur late fees, and or penalties, as provided herein or as we determine, in our sole discretion. All cancellation fees will be provided in the Guidelines (<a href="https://instantpro.ug/faq">https://Instantpro.ug/faq</a>). We reserve the right to change, modify, increase, or decrease the amount and terms of the cancellation fees in our discretion from time to time. If we choose to do so, we will notify you by posting the update to the Website.</p>

					<p>i. <i>Cancelling On Demand Jobs</i>. A Requesting User may cancel and will not be charged a cancellation fee for cancellation before the Instant Professional departs his or her location for the Premises or if the Instant Professional does not arrive at the Premises within the time period prescribed for the Job. A Requesting User may cancel but will be charged a cancellation fee for cancellation after the Instant Professional has departed for the Premises. A Requesting User may not cancel a Job once the Instant Professional has arrived at the Premises and notified the Requesting User of his or her arrival.</p>

					<p>ii. <i>Cancelling Later Jobs</i>. A Requesting User may cancel and will not be charged a cancellation fee for cancellation made before three hours prior to the start of the appointment window or if the Instant Professional does not arrive at the Premises within the time period prescribed for the Job. A Requesting User may cancel and be charged a cancellation fee for cancellation made after three hours prior to the start of the appointment window. A Requesting User may not cancel a Job once the Home Service Professional has arrived at the Premises and notified the Requesting User of his or her arrival.</p>

					<p>e. <b>Cancellation by an Instant Professional</b>. An Instant Professional may cancel a Job within a grace period (as provided in the Guidelines) after Accepting the Job or in extenuating services. If an Instant Professional cancels your Job, we will take reasonable efforts to match your Home Service Request with an alternate Instant Professional but is under no obligation to do so.</p>

					<ol start="2" type="1"> <li><b>Registration Data; Account Security</b>. In consideration of your use of the Service, you agree to: (a) provide us with accurate, current and complete information about you as may be prompted by any registration forms on the Service (<b>"Registration Data"</b>); and (b) maintain and promptly update the Registration Data, and any other information you provide to us, to keep it accurate, current and complete. We reserve the right to reject any registration form in our sole discretion. You must be at least 18 years old to register as a User or the age of majority in the jurisdiction in which you reside. By providing Registration Data, you signify that you are at least 18 years old and acknowledge that you may not use the Services if you are under the age of 18. If necessary, we may ask you for proof of your age. If you are unable to provide proof of your age, we reserve the right, at our sole discretion, to halt your registration. You may register on behalf of a corporate entity; however you acknowledge and agree that by providing Registration Data in such a capacity, you signify that you are authorized to enter into this Agreement on behalf of, bind the entity to, these terms and register for the Service and the App. Upon providing Registration Data to us through the Service, you will provide account information (your <b>"User Account"</b>) including (but not limited to) your personal information, and mobile telephone number. Once you successfully register for a User Account, you will choose a password and be given access to your personal User Account. You hereby agree to be fully responsible for (v) immediately updating your User Account to account for any change in Registration Data, (w) all use of your User Account, (x) any action that takes place using your User Account by any person or automated process, (y) maintaining the confidentiality and security of the password to your User Account, and (z) immediately notifying us upon any unauthorized use of your password or your User Account.</li>
					</ol><ol start="3" type="1"> <li><b>Fees &amp; Payment Terms</b></li>
					<ol start="1" type="a"> <li><b>Important Clarification Regarding Relationship</b>. Requesting Users contract directly with the Instant Professionals. We will not be a party to any agreements or contracts for Home Services. We act to coordinate payments between Requesting Users and the Home Services Professional but do not act as a prime contractor for the Home Services and nothing in our involvement in the payment process makes us responsible for the Home Services. Your contract for Home Services is with the Instant Professional, not with us.</li>
						<li><b>Instantpro Rates</b>. We verify the rates for Home Services (the <b>"Instantpro Rate"</b>), which will be given to your by the home services professionals after the site visit</li>
					</ol> </ol><p>. The Instantpro Rate includes any materials required by the Instant Professional to complete the Home Service. We reserve the right to modify or update the Instantpro Rates at any time and in our sole discretion. When submitting a Request for a particular category of Home Service, we may not be in position to provide you with the Instantpro Rate, and are under no obligation to do so and you hereby agree that it is your responsibility to wait for the verified Instantpro rates after a site visit by the professionals.</p>

					<ol start="3" type="1"> <ol start="3" type="a"> <li><b>Minimum Charge</b>. You understand and agree that there is a minimum charge set for each Home Service (the <b>"Minimum Charge"</b>). We reserve the right, in our sole discretion, to apply the Minimum Charge for your Job, other than as provided for herein. You understand and agree that we may apply the Minimum Charge to the Job if the Home Service Professional arrives at the Premises prior to any cancellation and within the grace period as set out in the Guidelines (<a href="https://instantpro.ug/faq">https://Instantpro.ug/faq</a>). If we choose to apply the Minimum Charge, we may consider the cost of materials separately from our determination of whether to apply the Minimum Charge.</li>
						<li><b>Home Service Payment and Billing</b>. Requesting Users will be responsible for paying the invoice for each Home Service (the <b>"Invoice"</b>), which will include the pricing terms of the Home Service agreed to between the Requesting User and the Instant Professional. By submitting a Request, you agree that you will pay for all Home Services requested (including all materials, taxes and late fees, as applicable) (the <b>"Home Service Payment"</b>) that may be accrued by or in connection with your User Account, unless otherwise provided in this Agreement. You understand and agree that we will be responsible, in our sole discretion, for determining the Home Service Payment amount and any agreement you make directly with the Instant Professional regarding payment will not apply. The Home Service Payment amount will be largely based on the information the Instant Professional provides us through the App or web system. For all charges applied to your User Account, you will have to make payment to us through your preferred method of payment as will be selected by you from our website and/or app according to the agreed upon amount between you and us for the Home Service, and you hereby accept to make this payment prior to us sending the professional. We reserve the right, in our sole discretion, but are under no obligation to place a hold on any Home Service Payment. You may be charged a cancellation fee or minimum payment if you book or confirm a Home Service Request but cancel it before the Home Service is completed as set out in the Guidelines. You further agree that you are responsible for the timely payment of all Home Service Payments and that any such Home Service Payment made is non-refundable, unless otherwise determined in our sole discretion, which includes our discretion to provide assistance under the Instantpro User Protection Plan (as defined herein). You may use Promotional Credits (as defined below) available in your User Account, if any, as full or partial payment for the Home Service Payments under the terms of this Agreement and any terms or restrictions attached to the Promotional Credits.</li>
					</ol> </ol><ol start="3" type="1"> <ol start="5" type="a"> <li><b>Payment options</b>. Users are required to pay for the selected home service by choosing from the available options within the web or the app. This options may change from time to time, as will and shall be determined at our sole discretion. By registering for our service, you acknowledge and agree the terms of the payment option will govern your agreement and interaction with the payment options and that our terms and policies do not govern and that we have no liability arising from the use of our payment options.</li>
				</ol> </ol><ol start="3" type="1"> <ol start="6" type="a"> <li><b>Our Fees</b>. There is currently no charge for your use of the Service, to the extent this includes browsing the Website, downloading the App, Requesting Home Services, and reviewing Home Services provided by Home Service Professionals. We reserve the right to introduce or charge, or change a service fee (<b>"Instantpro Fees"</b>) or implement charges for features of the Service as indicated to Users from time to time. Any revised fees will take effect 30 days from the date of posting to the Website, App, or notification to your User Account. If you choose to terminate your User Account after notification of any new or additional fees, you must do so before the 30 day period, after which such charges will be applied to your User Account, if applicable.</li>
			</ol> </ol><ol start="3" type="1"> <ol start="7" type="a"> <li><b>No Obligation to Withhold Taxes</b>. Except for applicable taxes indicated on your Invoice, we do not collect or remit any taxes for any Home Service Payments received in any jurisdiction. The payment rate used for computing Home Service Payments paid to Home Service Professionals is inclusive of any and all applicable state, local, or other fees or taxes owed by such Home Service Professionals. You acknowledge and agree that you are solely responsible for all tax compliance relating to your use of our Service and that in no event will we be responsible for any tax compliance. You further agree to indemnify and hold the Instantpro Companies and each of their directors, officers, agents, contractors, partners and employees, harmless from and against any loss, liability, claim, demand, damages, costs and expenses, including reasonable attorney's fees, arising out of or in connection with any claims by the Uganda Revenue Authority or any taxes related to your use of the Service.</li>
		</ol> </ol><ol start="3" type="1"> <ol start="8" type="a"> <li><b>Promotions and Promotional Credits</b>. We may, from time to time and in our sole discretion, provide certain promotional credits (<b>"Promotional Credits"</b>) to Users. There is no guarantee of or right to receive any such Promotional Credits. We reserve the right to activate, modify, or delete any such Promotional Credits at any time, in our sole discretion and without notice to you. Promotional Credits are non-transferrable, have no cash value, and will expire no later than 90 days from the date issued to your User Account.</li>
	</ol> </ol><ol start="4" type="1"> <li><b>Prohibited Activities and Services</b>. Without limiting Section 10:</li>
	<ol start="1" type="a"> <li><b>Prohibited Activities</b>. Trust is a critical element of the Service. While using the Service, you agree not to:</li>
		<ol start="1" type="i"> <li>if you are a Requesting User, submit a Request that you do not intend to have completed by a Home Service Professional or that you do not intend to pay for,</li>
			<li>if you are a Home Service Professional, accept a Request that you do not actually wish to accept or complete, or that you are not skilled, licensed (where applicable) or competent to complete,</li>
			<li>recruit or otherwise solicit any User or Home Service Professional to join third-party services or websites that are competitive to Instantpro or to use our Services to obtain work or Home Services outside the provision of our Service, or</li>
			<li>Use the Service to "stalk", harass, threaten, intimidate, harm, cause a nuisance to, annoy, or inconvenience any other User of the Service or collect or store any personally identifiable information about any other User other than for purposes of transacting a Home Service.</li>
		</ol> </ol> </ol><ol start="4" type="1"> <ol start="2" type="a"> <li><b>Prohibited Services</b>. While using the Service, you further agree not to request, offer, negotiate, or complete any portion of a Home Service that:</li>
		<ol start="1" type="i"> <li>would violate, or lead to the violation of, any applicable local, provincial, territorial, national or international law or regulation,</li>
			<li>encourage or facilitate illegal activity, pornographic or obscene services including sexual and escort services, offers and solicitations of prostitution, and pornography,</li>
			<li>you have no legal right to request or perform, or</li>
			<li>would be considered, in any way, to form part of a lottery, raffle, sweepstakes, affiliate marketing scheme, multilevel marketing, pyramid scheme, or be related to spam, or any other form of solicitation that is not authorized by this Agreement</li>
		</ol> </ol> </ol><ol start="5" type="1"> <li><b>Amendments</b>. We reserve the right to change, modify, add, or delete portions of this Agreement in our sole discretion from time to time without further notice. If we do this, we will post the latest version of this Agreement on this page at <a href="https://instantpro.ug/terms_and_conditions">https://Instantpro.ug/terms_and_conditions</a>, and we will indicate at the bottom of such page the date of the last revision or modification. Your continued use of the Service, which use includes your continuing to make available your User Content (defined below) on the Service, after any such change, modification, addition or deletion constitutes your acceptance of the Agreement as then revised. If you do not agree to abide by this or any future version of the Agreement, do not use or access (or continue to use or access) the Service. It is your responsibility to regularly check this page to determine if there have been changes to this Agreement and to review such changes.</li>
	</ol><ol start="6" type="1"> <li><b>Content</b>. In this Agreement, <b>"Content"</b> means all materials and content of any type, including, but not limited to, ratings, photos, graphics, images, designs, profiles, messages, information, notes, text, information (including Registration Data, Requests, location), music, sound, video, articles, and software.</li>
</ol><ol start="7" type="1"> <li><b>User Content and Your License to Us</b>. The Service permits you (or any person using your User Account) to submit, transmit, copy, make available and distribute Content (collectively, your <b>"User Content"</b>), and we do not claim ownership over any User Content. By providing any User Content, you</li>
<ol start="1" type="a"> <li>acknowledge that the Instantpro Companies reserve the right to refuse to accept, display, or transmit any User Content in its sole discretion,</li>
	<li>grant the Instantpro Companies the worldwide, royalty-free, non-exclusive right and license to use, distribute, reproduce, modify, adapt, perform and display such User Content as permitted by the functionality of the Service (the <b>"User License"</b>) on the following terms:</li>
	<ol start="1" type="i"> <li>The User License is limited to the purpose of offering the Service,</li>
		<li>The User License includes the Instantpro Companies' right to sublicense to third party service providers for the sole purpose of offering the Service, at all times in accordance with this Agreement, and</li>
		<li>The User License will end, and the Instantpro Companies will cease to use User Content, a commercially reasonable period after such User Content is removed from the Service,</li>
	</ol> </ol> </ol><ol start="7" type="1"> <ol start="3" type="a"> <li>represent and warrant to us that (1) you have all right, title and interest to grant the User License, (2) the User Content does not infringe on any other person's copyright, trade-mark, proprietary interests, trade secrets, privacy or other intellectual property rights, and (3) no User Content contains any libelous, defamatory or otherwise unlawful material, and</li>
	<li>hereby agree to indemnify us and hold us harmless from any claims, losses, damages or expenses incurred by us in respect of any third party claims that your User Content infringes on any other person's rights (including all of the rights set out in (b) above).</li>
</ol> </ol><ol start="8" type="1"> <li><b>Service Content</b>. All Content available or stored on the Service other than your User Content, including the Service itself, including the Website and the App, all other Users' Content, any Content made available by the Instantpro Companies or any third party, and the selection and arrangement of all such Content and User Content (collectively, the <b>"Service Content"</b>), is the proprietary property of us, the Users or our licensors with all rights reserved, and the Instantpro Companies (or, as applicable, our Users or licensors) retain and shall retain all right, interest and title in and to all Service Content.</li>
</ol><ol start="9" type="1"> <li><b>Our License to You</b>. Provided that you are eligible for use of the Service, and that you agree to this Agreement, we hereby grant you a limited, personal, non-transferable, revocable (at any time with or without notice or cause) and non-exclusive right and license to access and use the Service and to download or print a copy of any portion of the Service Content solely for your personal, non-commercial use, and for such use expressly permitted by this Agreement, subject to this Agreement and provided that you keep all copyright or other proprietary notices intact. You agree to respect all copyright and other legal notices, information, and restrictions contained in any content accessed through the Website or the App. You further agree not to change, translate, or otherwise create any derivative works of the Service. If we revoke our license to you, you agree to remove any Content infringing the terms of this Agreement and that the terms of the Agreement will survive such revocation and continue to bind you.</li>
</ol><ol start="10" type="1"> <li><b>User Conduct (Things You Must Not Do)</b>. You acknowledge and agree that the Service is available for your personal use only in connection with the proper requesting or servicing of Requests, and may not be used for any other commercial purpose. Without restricting anything else in this Agreement, you agree not to</li>
<ol start="1" type="a"> <li>Alter, modify, copy, distribute, frame, reproduce, republish, download, display, post, transmit, or sell in any form or by any means, in whole or in part, Service Content,</li>
	<li>Except to the extent required to be permitted by the law of your jurisdiction, reverse engineer, decompile, or disassemble, translate or otherwise attempt to extract the source code from the Service, the Service Content, or any part thereof,</li>
	<li>Make the Service or Service Content available to anyone, or permit anyone to access same, nor license, sublicense, sell, resell, publish, republish, transfer, assign, distribute, rent, lease, time-share, copy or otherwise commercially exploit the Service in any way except in furtherance of your permitted use in accordance with this Agreement,</li>
	<li>Republish any Service Content on any Internet, Intranet or Extranet site or incorporate the information in any other database or compilation, without our prior written permission or the permission of the particular Content owner, as the case may be,</li>
	<li>Use any data mining, robot or similar data gathering or extraction methods with respect to any Service or any Service Content,</li>
	<li>register for more than one User Account, register for a User Account on behalf of an individual other than yourself, or register for a User Account on behalf of any group or non-individual entity (except if you are duly authorized to do so by such group or entity),</li>
	<li>Impersonate any person or entity, or falsely state or otherwise misrepresent yourself, your age or your affiliation with any person or entity, in your Registration Data, User Account or otherwise,</li>
	<li>Upload, post, transmit, share or otherwise make available on the Service any User Content that</li>
	<ol start="1" type="i"> <li>Consists of any unsolicited or unauthorized advertising, solicitations, promotional materials, "junk mail", "spam", "chain letters", "pyramid schemes", or any other form of solicitation, or</li>
		<li>Contains any private information of any third party, including, without limitation, addresses, phone numbers, email addresses, Social Insurance Numbers, US Social Security numbers, credit card numbers, financial information and other personally identifying or private information, unless that third party has consented to such use of its private information,</li>
		<li>In our sole discretion, is harmful, threatening, unlawful, defamatory, infringing, abusive, inflammatory, harassing, vulgar, obscene, fraudulent, invasive of privacy or publicity rights, hateful, or racially, ethnically or otherwise objectionable,</li>
		<li>Contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment, or</li>
		<li>Would constitute, encourage or provide instructions for a criminal offense, violate the rights of any party, or that would otherwise create liability or violate any local, state, national or international law,</li>
	</ol> <li>Disable or circumvent any access control or related process or procedure established with respect to the Service, or attempt to gain unauthorized access to the Service or Service Content,</li>
	<li>Remove any copyright or other proprietary notices on or in the Service, Service Content or any part thereof,</li>
	<li>Solicit personal information from anyone under 18 or solicit passwords or personally identifying information from any person for commercial or unlawful purposes,</li>
	<li>Use the Service or any Service Content to "stalk", intimidate, harm or otherwise harass another User or another person,</li>
	<li>intentionally or unintentionally violate any applicable local, state, national or international law, including any regulations thereto, or any court order or lawful order of any governmental authority,</li>
	<li>Access the Service or any Service Content in order to (i) build a competitive product or service, or (ii) copy any features, functions or graphics of the Service or Service Content,</li>
	<li>Utilize the Service in any way except as expressly permitted by this Agreement, including by developing or using any software tool or other application that interfaces with the Service, Website, or App except for standard web browsers,</li>
	<li>Interfere with or disrupt the Service or Service Content (including the servers, networks or technology connected to the Service), or</li>
	<li>Use or attempt to use another's User Account or the Service without express authorization from us or the applicable User.</li>
</ol> </ol><ol start="11" type="1"> <li><b>Nudity and Objectionable Material</b>. You acknowledge and agree that the Service must remain a safe site for families with children, so you agree not to, and we strictly prohibit, the uploading and display of any User Content portraying explicit nudity, adult content, or that is unacceptable for viewing by minors or objectionable, in our sole discretion. For example, but without limitation, prohibited User Content would include material that would be unacceptable in a public museum where minors visit, or User Content that would only be appropriate for adult sites, adult magazines, or R-rated movies. You acknowledge and agree that the sole discretion of whether User Content is suitable belongs to us, and we reserve the right (but have no obligation) to (a) delete any User Content we deem to violate this Agreement or, or (b) to cancel the User Account from which such User Content made available on the Service.</li>
</ol><ol start="12" type="1"> <li><b>User Content Responsibility</b>. You acknowledge and agree that (a) you are solely responsible for all of your User Content, and (b) we may, but are not obligated to, review and delete or remove (without notice) any User Content, in our sole discretion, including, without limitation, any User Content that violates this Agreement. You agree that you must evaluate, and bear all risks associated with, the use of any User Content, including any reliance on the accuracy, completeness, or usefulness of such Content. In this regard, you acknowledge that you may not rely on any Service Content (except for this Agreement, the Privacy Policy and other legally binding agreements) for any purpose whatsoever. You will also comply with any of your own local laws regarding online conduct and acceptable content, including laws relating to the export of data if you are outside of Canada.</li>
</ol><ol start="13" type="1"> <li><b>Other Uses</b>. Any use of the Service or the Service Content other than as specifically authorized in this Agreement, without our prior written permission, is strictly prohibited and will automatically terminate all licenses granted by us herein. Such unauthorized use may also violate applicable laws including, without limitation, copyright, privacy, trade-secrets and trademark laws and applicable communications regulations and statutes. Unless explicitly stated herein, nothing in this Agreement shall be construed as conferring any other license to intellectual property rights, whether by estoppel, implication or otherwise.</li>
</ol><ol start="14" type="1"> <li><b>Modifications to Service</b>. We reserve the right at any time and from time to time to perform maintenance on, to add to, to remove from, to make upgrades and updates to, to suspend, and to modify the Service or any part thereof with or without notice. NOTWITHSTANDING ANY PROVISION HEREIN, YOU AGREE THAT WE SHALL NOT BE LIABLE IN ANY MANNER TO YOU OR TO ANY THIRD PARTY FOR ANY SUCH MAINTENANCE, ADDITION, REMOVAL, UPGRADE, UPDATE, SUSPENSION OR MODIFICATION.</li>
</ol><ol start="15" type="1"> <li><b>General Practices Regarding Use and Storage</b>. You acknowledge that we may establish general practices and limits concerning use of the Service, including, without limitation, the maximum number of days that User Content will be retained by the Service, the maximum number of User Content that may be transmitted, posted, shared, used, copied, or otherwise made available on the Service (whether per User Account or globally), the maximum size of any User Content, the maximum disk space that will be allotted on the Service servers on any User's behalf, and the maximum number of times (and the maximum duration for which) any User may access the Service in a given period of time. You agree that we have no responsibility or liability for the deletion or failure to store any User Content and other communications or Content maintained or transmitted by the Service. You acknowledge that we reserve the right to log off or otherwise disconnect any User Account that is inactive for an extended period of time in our sole discretion.</li>
</ol><ol start="16" type="1"> <li><b>Termination</b>. You may terminate your User Account at any time by deleting your User Account. We reserve the right to terminate, suspend, or deactivate your User Account if we suspect or determine, in our sole discretion, that you have misused our Services, have used our Services to violate any law or have breached any term of this Agreement. We will give you notice of such deactivation and you agree to immediately cease all use of our Services and any Service Content or Content licensed to you in Section 9 of this Agreement.</li>
</ol><ol start="17" type="1"> <li><b>Trademarks</b>. Notwithstanding anything else in this Agreement, "Instantpro", the Instantpro logo and design, and all other trade-marks, trade dress, graphics, logos, designs, page headers, button icons, scripts and service names used by the Instantpro Companies on or in connection with the Service (collectively, the <b>"Marks"</b>) are registered trademarks, trademarks or trade dress of the Instantpro Companies or our licensors and all right, title and interest in and to the Marks, whether registered or not, are and shall remain vested in us or in our licensors, as applicable. The Marks may not be used, including as part of trademarks, trade names, trade dress or as part of domain names, in connection with any product or service in any manner that is likely to cause confusion and may not be copied, imitated, or used, in whole or in part, without our prior written permission.</li>
</ol><ol start="18" type="1"> <li><b>Third Party Sites and Content</b>. The Service may contain (or you may be presented with through the Service) links to other web sites (<b>"Third Party Sites"</b>) as well as Content (for example GPS systems) belonging to or originating from parties other than us or our Users (the <b>"Third Party Content"</b>). Such Third Party Sites and Third Party Content are not investigated, monitored or checked for accuracy, appropriateness, or completeness by us, and we are not responsible for any Third Party Sites accessed through the Service or any Third Party Content available on the Service, including, without limitation, the content, accuracy, safety, functioning, offensiveness, opinions, reliability or policies of or contained in the Third Party Sites or the Third Party Content. The inclusion of or linking to any Third Party Site or any Third Party Content does not imply approval or endorsement thereof by us and does not guarantee that any Third Party Content will function with the Service or will be error-free. If you decide to leave the Service and access the Third Party Sites, you do so at your own risk and you acknowledge and agree that our terms and policies do not govern same and that we have no liability arising from your use of or access to any Third Party Site or Third Part Content. You should review the applicable terms and policies, including privacy and data gathering practices, of any Third Party Site to which you navigate from the Service. Reference on the Service to any products, services, processes or other information, by trade name, trademark, manufacturer, supplier or otherwise, does not constitute or imply (a) endorsement, sponsorship or recommendation thereof by, or (b) or any affiliation thereof with the Instantpro Companies. Further, we are in no way responsible for references to or representations, endorsements, reviews, recommendations or sponsorship of the Service or any Home Service Professional on any Third Party Site.</li>
</ol><ol start="19" type="1"> <li><b>Advertisements</b>. We may run advertisements and promotions on the Service. You agree that we have the right to run such advertisements and promotions. The manner, mode and extent of advertising by us on the Service is subject to change in our sole discretion.</li>
</ol><ol start="20" type="1"> <li><b>User-and-User Disputes and Release</b>. The Service is only a venue for connecting Users. We are not involved in the actual contact between Users or in the provision of Home Services and you are solely responsible for your interactions with other Users. If you have a dispute with one or more Users, you release the Instantpro Companies (and our officers, directors, agents, investors, subsidiaries, and employees) from any and all claims, demands, or damages (actual or consequential) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, direct or indirect arising out of or in any way connected with such disputes.</li>
</ol><ol start="21" type="1"> <li><b>Disclaimers</b></li>
<ol start="1" type="a"> <li><b>No Responsibility for Others' Content</b>. We are not responsible or liable in any manner for any User Content or Third Party Content available on the Service, whether made available or caused to be made available by Users or by any of the technology associated with or utilized in the Service. Although we provide this Agreement and other policies and rules for User conduct, we do not control and are not responsible for our Users' actions and are not responsible for any Content you may encounter on the Service, be it User Content or Third Party Content. We are not responsible for the conduct, whether online or offline, of any User. Notwithstanding anything else in this Agreement, the Instantpro Companies have no responsibility to monitor any User Content or Third Party Content.</li>
	<li><b>Availability</b>. The Service may be temporarily unavailable from time to time for maintenance or other reasons. We assume no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, User Content. We are not responsible for any problems or technical malfunction, including, without limitation, any problem or malfunction of any telephone network or lines, computer online systems, servers or providers, computer equipment, software, failure of email or persons, traffic congestion on the Internet or at any web site (including the those in the Service) or combination thereof.</li>
	<li><b>No Guarantee</b>. We make no guarantee regarding the provision of Home Services, the acceptance of any Requests for the provision of Home Services, the availability, workmanship, timeliness, integrity, ability or skill of Home Service Professionals or the Home Services they purport to be able or willing to provide. We do not guarantee that the Home Service Professionals hold any qualification, certification, licence, schooling, training, or insurance required to provide the Home Services. THE COMPANY DOES NOT WARRANTY ANY HOME SERVICE PROFESSIONAL'S PROFESSIONAL ACCREDITATION, REGISTRATION, CERTIFICATION, LICENSE, INSURANCE, BOND, OR WORKER'S COMPENSATION PROTECTION REGALATED TO A HOME SERVICE.</li>
	<li><b>AS IS; AS AVAILABLE</b>. THE SERVICE AND THE SERVICE CONTENT ARE PROVIDED "AS IS" AND "AS AVAILABLE" AND THE INSTANTPRO COMPANIES DISCLAIM ANY AND ALL REPRESENTATIONS AND WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. THE INSTANTPRO COMPANIES CANNOT GUARANTEE AND DO NOT PROMISE ANY SPECIFIC RESULTS FROM USE OF THE SERVICE OR MAKE ANY WARRANTY AS TO THE TIMELINESS, ACCURACY, RELIABILITY, COMPLETENESS, OR QUALITY OF ANY HOME SERVICE, INFORMATION OR MATERIALS PROVIDED THROUGH OR IN CONNECTION WITH THE USE OF THE SERVICE. THE INSTANTPRO COMPANIES DO NOT REPRESENT OR WARRANT THAT THE SERVICE CONTENT IS ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERROR-FREE, OR THAT THE SERVICE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. THEREFORE, YOU SHOULD EXERCISE CAUTION IN THE USE AND DOWNLOADING OF ANY SUCH CONTENT AND USE INDUSTRY-RECOGNIZED SOFTWARE TO DETECT AND DISINFECT VIRUSES. THE INSTAPRO COMPANIES DISCLAIM ANY AND ALL RESPONSIBILITY FOR ANY THIRD PARTY CONTENT OR THIRD PARTY SITES.</li>
</ol> </ol><ol start="22" type="1"> <li><b>Limitation on Liability</b>. EXCEPT IN JURISDICTIONS WHERE SUCH PROVISIONS ARE RESTRICTED (AND, THEN, ONLY TO THE STRICT EXTENT OF SUCH RESTRICTION),</li>
<ol start="1" type="a"> <li>IN NO EVENT WILL THE INSTANTPRO COMPANIES, OR THEIR DIRECTORS, PARTNERS, OFFICERS, EMPLOYEES, CONTRACTORS OR AGENTS, BE LIABLE TO YOU OR ANY THIRD PERSON FOR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES, INCLUDING, WITHOUT LIMITATION, AND WHETHER DIRECT OR INDIRECT, FOR ANY LOST PROFITS, LOST BUSINESS OPPORTUNITIES, LOST DATA, THE COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, ANY PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, ARISING FROM YOUR USE OF THE SERVICE, THE SERVICE CONTENT OR OTHER MATERIALS ON OR ACCESSED THROUGH THE SERVICE (INCLUDING ALL THIRD PARTY CONTENT AND THIRD PARTY SITES), EVEN IF THE INSTAPRO COMPANIES ARE AWARE OR HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND</li>
	<li>NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, THE INSTANTPRO COMPANIES' LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER, AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO THE AMOUNT PAID, IF ANY, BY YOU TO THE INSTANTPRO COMPANIES FOR THE SERVICE DURING YEAR IN WHICH YOUR SUCH CAUSE AROSE (FOR EXAMPLE, IF YOU ARE A HOME SERVICE PROFESSIONAL, THE AMOUNT OF YOUR SERVICE FEES). YOU ACKNOWLEDGE THAT THE SERVICE IS FREE FOR REQUESTING USERS. NOTWITHSTANDING THE ABOVE, IN NO CASE WILL THE INSTANTPRO COMPANIES' LIABILITY TO YOU EXCEED THE LESSER OF (I) 20% OF TOTAL COST OF THE HOME SERVICES RENDERED IN A CALENDAR YEAR AND (II) $100. YOU ACKNOWLEDGE THAT IF NO SUCH FEES ARE PAID BY YOU TO THE INSTANTPRO COMPANIES FOR THE SERVICE, YOU SHALL BE LIMITED TO INJUNCTIVE RELIEF ONLY, UNLESS OTHERWISE PERMITTED BY LAW, AND SHALL NOT BE ENTITLED TO DAMAGES OF ANY KIND FROM THE INSTANTPRO COMPANIES, REGARDLESS OF THE CAUSE OF ACTION. YOU FURTHER ACKNOWLEDGE THAT ANY PROTECTION PROVIDED UNDER THE INSTANTPRO USER PROTECTION PLAN IS IN OUR SOLE DISCRETION AS IS INTENDED TO INCREASE THE USER EXPERIENCE AND IS IN NO WAY AN ACCEPTANCE OR ADMISSION OF LIABILITY. THE INSTANTPRO COMPANIES DO NOT ACCEPT ANY LIABILITY WITH RESPECT TO THE QUALITY OF FITNESS OF ANY WORK PERFORMED VIA THE SERVICE.</li>
</ol> </ol><p>CERTAIN JURISDICTIONS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS BUT ONLY TO THE EXTENT OF SUCH EXCLUSION BY APPLICABLE LAW. NOTHING IN THIS AGREEMENT IS INTENDED TO EXCLUDE OR LIMIT ANY CONDITION, WARRANTY, RIGHT OR LIABILITY THAT MAY NOT BE LAWFULLY EXCLUDED OR LIMITED.</p>

<ol start="23" type="1"> <li><b>Instantpro User Protection Plan</b>. We may choose, in our sole discretion, to provide a user protection plan (the <b>"Instantpro User Protection Plan"</b>), to provide protection to Requesting Users of Home Service Professionals who are not satisfied with the provision of a Home Service requested through our Services. If a Requesting User is not reasonably satisfied with the performance of his or her requested Home Service or Job, and that Requesting User, in our sole discretion, meets all terms and conditions of the Instantpro User Protection Plan available here (<a href="https://instantpro.ug/satisfaction_guarantee">https://Instantpro.ug/satisfaction_guarantee</a>) (the <b>"Instantpro User Protection Plan Terms"</b>) we may, in our sole discretion and pursuant to the Instantpro User Protection Plan Terms, seek to fix the problem, using the same or another Home Service Professional, or reimburse you for the Home Service Payment amount you have paid for the Home Service. Notwithstanding the foregoing, the maximum amount we may incur or pay you for a claim under the Instantpro User Protection Plan, if any, will not exceed the total amount of the Home Service Payment paid by you. Any protection afforded from the Instantpro User Protection Plan is subject to certain conditions, limitations and exclusions, as described in the terms of the Instantpro User Protection Plan available at <a href="https://instantpro.ug/satisfaction_guarantee">https://Instantpro.ug/satisfaction_guarantee</a> (the <b>"Instantpro User Protection Plan Terms"</b>).</li>
</ol><ol start="24" type="1"> <li><b>No Agency</b>. You hereby acknowledge and agree that no employment, joint venture, partnership, or agency relationship exists between you and any of the Instantpro Companies as a result of this Agreement or your use of our Services. We are solely independent contractors.</li>
</ol><ol start="25" type="1"> <li><b>Privacy</b>. We care about the privacy of our Users. You can view our privacy policy at <a href="https://instantpro.ug/privacy_policy">https://Instantpro.ug/privacy_policy</a>. Without limiting that, you acknowledge that we may (but have no obligation to) access, preserve and disclose your User Account data and any User Content if, in good faith, we believe that same is reasonably needed to (a) comply with applicable law or legal process, (b) enforce this Agreement, (c) protect against imminent harm to any person, any safety of any person, or any property of any person, or (d) such access, preservation, or disclosure is permitted under applicable law. You further acknowledge that the Service uses the Internet and other, third-party networks, and that, accordingly, any information processed using the Service may be processed or transmitted over various networks (including those outside of our control).</li>
</ol><ol start="26" type="1"> <li><b>Copyright, Intellectual Property and Content Complaints</b>. If you believe that any Content on the Service infringes upon any copyright or other intellectual property right that you own or control, or if you otherwise object to any User Content that you find on the Service, you may send a written notification to our designated agent for copyright and other complaints:</li>
</ol><p>· by e-mail: <a href="mailto:info@instantpro.ug">info@instantpro.ug</a> </p>

<ol start="27" type="1"> <li>The notification must be a written communication that includes the following:</li>
</ol><ol start="27" type="1"> <ol start="1" type="a"> <li>a physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</li>
<li>if the complaint is about copyright or other intellectual property rights, identification of the copyrighted work or other intellectual property right claimed to have been infringed, or, if multiple infringements are covered by a single notification, a representative list of such infringements;</li>
<li>if the complaint is about objectionable content, the reasons for the objection;</li>
<li>identification of the material that you are objecting to and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material;</li>
<li>information reasonably sufficient to permit us to contact the complaining party, such as an address, telephone number and, if available, an electronic mail address at which the complaining party may be contacted;</li>
<li>a statement that the information in the notification is accurate; and</li>
<li>if the complaint is about copyright or other intellectual property rights, a statement under penalty of perjury, that (i) the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed, and (ii) the complaining party has a good-faith belief that use of the material in the manner complained of is not authorized by the owner thereof, its agent or the law.</li>
</ol> </ol><ol start="28" type="1"> <li><b>Abuser and Repeat Abuser Policy</b>. We have adopted a policy of terminating, in appropriate circumstances and at our sole discretion, members who are deemed to be repeat infringers of intellectual property or users or posters of objectionable content. We may also, at our sole discretion, limit access to the Service or terminate the User Account of any User who infringes any intellectual property rights of us or others, whether or not there is any repeat infringement, or otherwise uses or posts objectionable content through the Service.</li>
</ol><ol start="29" type="1"> <li><b>Governing Law; Venue and Jurisdiction</b>. You agree that the laws of the Republic of Uganda, without regard to principles of conflict of laws, will govern this Agreement and any dispute of any sort that might arise between you and us. You hereby irrevocably attorn to the exclusive jurisdiction of the Courts of the Republic of Uganda with respect to any dispute hereunder.</li>
</ol><ol start="30" type="1"> <li><b>Dispute Resolution</b>.</li>
<ol start="0" type="a"> <li><b>Contact Us First</b>. We care about addressing your concerns in an informal and efficient manner. For any dispute you have with us regarding the Services, you agree to first contact us and attempt in good faith to resolve the dispute informally by reporting the dispute to our customer service online at any time by emailing <a href="mailto:info@instantpro.ug">info@instantpro.ug</a>. You agree that if our dispute is not resolved by informal resolution within 15 days of your submission or within a reasonable time under the Instantpro User Protection Plan, you will resolve any claims through final and binding arbitration (<b>"Arbitration"</b>).</li>
	<li><b>Arbitration</b>. You agree that any claim arising out of or in connection with this Agreement, or in respect of any legal relationship associated with or derived from this Agreement, that is not resolved through our customer service centre, will be finally resolved by Arbitration under the relevant clauses in the constitution of the Republic of Uganda. The Arbitration will take place in Uganda and the language of the arbitration will be English.</li>
	<li><b>No Class Actions</b>. You hereby agree and acknowledge that you may only resolve disputes with us on an individual basis, and may not bring a claim as a plaintiff or a class member in a class, purported class, consolidated, or representative action. You further agree that, by entering into these terms, you and the Instantpro Companies each agree that all claims and disputes shall be resolved under this Agreement. You further waive any constitutional or statutory right to go to court and have a trial in front of a judge or jury on an individual, class action, or representative action basis. In the event any litigation should arise between you and us, in any jurisdiction, in a suit to vacate or enforce an Arbitration award or otherwise, you and the Instantpro Companies waive all rights to a jury trial, instead electing that the dispute be resolved by a judge, and agree to take any and all action necessary or appropriate to effect such waiver.</li>
	<li><b>Statute of Limitations</b>. You hereby agree that any claim under this Agreement must be brought within one year of the act giving rise to the claim.</li>
</ol> </ol><ol start="31" type="1"> <li><b>Indemnity</b>. You agree to indemnify and hold the Instantpro Companies and each of their directors, officers, agents, contractors, partners and employees, harmless from and against any loss, liability, claim, demand, damages, costs and expenses, including reasonable attorney's fees, arising out of or in connection with any User Content and any Third Party Content, your use of the Service, your conduct in connection with the Service or with other Users of the Service, or any violation of (a) this Agreement, (b) any law, or (c) any right of any third party.</li>
</ol><ol start="32" type="1"> <li><b>Submissions</b>. Notwithstanding any term herein related to User Content, you acknowledge and agree that any questions, comments, complaints, suggestions, ideas, feedback or other information about the Service (collectively, <b>"Submissions"</b>), provided by you to us are non-confidential and shall become the sole property of the Instantpro Companies, who shall own exclusive rights, including all intellectual property rights, and shall be entitled to the unrestricted use and dissemination thereof for any purpose, commercial or otherwise, without acknowledgment or compensation to you.</li>
</ol><ol start="33" type="1"> <li><b>Electronic Communications</b>. When you use the Service, send e-mails to us, or register for a User Account, you are communicating with us electronically. You consent to receive communications from us electronically. We will communicate with you by e-mail to the email address attached to your User Account through your Registration Data or by posting notices on the Website. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.</li>
</ol><ol start="34" type="1"> <li><b>App/Mobile Phone Use</b>. You agree to adhere to any terms of any app store, mobile software platform, payment platform, or other third party services provided in connection with your use of the App. We reserve all rights in and to the App not expressly granted to you under this Agreement and you only have a limited license to use it to access the Service in accordance with these terms. By providing your mobile phone number and using the Service, you hereby affirmatively consent to our use of your mobile phone number for calls and texts from us and certain other Home Service Professionals relating to Requests relevant to you, such as those you submit. You understand and acknowledge that by communicating by calls or text, standard message charges or other charges from your wireless carrier may apply. You may opt-out of receiving text messages from us by modifying your User Account settings on the Website or App or by emailing <a href="mailto:info@instantpro.ug">info@instantpro.ug</a>. </li>
</ol><ol start="35" type="1"> <li><b>Merger or Acquisition</b>. It is possible that any of the Instantpro Companies may be acquired or transferred as part of a merger, acquisition or other change of control. In the event of such a transaction, you understand and agree that we may assign our rights under this Agreement and that your personal information may be transferred to the succeeding entity in accordance with our Privacy Policy.</li>
</ol><ol start="36" type="1"> <li><b>Interpretation</b>. Headings are for convenience only and shall not be used to interpret, or as a guide for interpretation of, this Agreement. The word "or" is not exclusive and the word "including" is not limiting (whether or not non-limiting language such as "without limitation" or "but not limited to" or other words of similar import are used with reference thereto). A word importing the masculine gender includes the feminine and neuter, a word in the singular includes the plural, a word importing a corporate entity includes an individual, and vice versa and "person" will mean an individual, partnership, corporation (including a business trust), joint stock company, trust unincorporated association, joint venture, or other entity or a government or any agency, department or instrumentality thereof and vice versa.</li>
</ol><ol start="37" type="1"> <li><b>Other</b>. This Agreement constitutes the entire agreement between you and us regarding the use of the Service, superseding any prior agreements between you and us relating to your use of the Site or the Service. Our failure to exercise or enforce any right or provision of this Agreement shall not constitute a waiver of such right or provision in that or any other instance. If any provision of this Agreement is held invalid, unlawful, void or unenforceable for any reason, that provision shall be deemed severable and the remainder of this Agreement shall continue in full force and effect. This Agreement shall ensure to the benefit of, and be binding upon, parties hereto and their respective heirs, executors, administrators, successors, and assigns.</li>
</ol><ol start="38" type="1"> <li><b>English Language</b>. The parties have requested and agree that this Agreement and all documents relating thereto be drawn up in English. </li>
</ol><p><b><i>End of Terms of Service (Last Updated: June, 2017)</i></b></p>


</div>
</div>
</div>
</div>
</div>
@endsection
